# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20170616_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='position',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.IntegerField(blank=True, choices=[(0, '--------'), (1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u4ea4\u6362\u673a'), (4, '\u8def\u7531\u5668'), (5, '\u9632\u706b\u5899'), (6, 'Docker'), (7, '\u5176\u4ed6')], null=True, verbose_name='\u4e3b\u673a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='env',
            field=models.IntegerField(blank=True, choices=[(0, '--------'), (1, '\u751f\u4ea7\u73af\u5883'), (2, '\u6d4b\u8bd5\u73af\u5883')], null=True, verbose_name='\u8fd0\u884c\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '--------'), (1, '\u5df2\u4f7f\u7528'), (2, '\u672a\u4f7f\u7528'), (3, '\u62a5\u5e9f')], default=1, null=True, verbose_name='\u673a\u5668\u72b6\u6001'),
        ),
    ]
