# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysql_db_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, verbose_name='\u4e3b\u673a')),
                ('port', models.CharField(max_length=50, verbose_name='\u7aef\u53e3')),
                ('dbname', models.CharField(max_length=100, verbose_name='\u6570\u636e\u5e93')),
                ('db_info', models.CharField(max_length=300, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.CharField(max_length=10, null=True, verbose_name='Databas\u72b6\u6001,1\u8868\u793a\u589e,0\u8868\u793a\u5220')),
            ],
            options={
                'verbose_name': 'db\u4fe1\u606f',
                'verbose_name_plural': 'db\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='mysql_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7ec4ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='\u4e3b\u673a')),
                ('port', models.CharField(max_length=50, verbose_name='\u7aef\u53e3')),
                ('m_hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6240\u5c5e\u7ec4MASTER')),
                ('m_port', models.CharField(blank=True, max_length=100, null=True, verbose_name='MASTER\u7aef\u53e3')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.BooleanField(default=True, verbose_name='\u6570\u636e\u5e93\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u5e93\u4fe1\u606f',
                'verbose_name_plural': '\u6570\u636e\u5e93\u4fe1\u606f',
            },
        ),
    ]
